### ISSUE TITLE
1 блок "Любимовка еще"

### ISSUE THREAD

**Issue by AlenaNikitiina** [AlenaNikitiina/lubimovka#1]
- [x] title
- [x] p
- [x] foto
- [x] button

**Comment by Kripns** [comment]
Блок готов. Добавил стили для кнопки. Чтоб переиспользовать компонент кнопки в др блоках, нужно добавить элементу класс square-button. Для кнопки с нижним/левым бордером добавляем модификатор square-button_border_left-bottom. Анимации ховера уже будут внутри.

**Comment by AlenaNikitiina** [comment]
Мы не используем в html caps lock. Исправь, пожалуйста.

**Comment by Kripns** [comment]
Исправил

**Comment by AlenaNikitiina** [comment]
.
